### ISSUE TITLE
Update code base to support a domain override resource to apend domains 

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-sandbox-bot#54]
The existing code base pulls in the `current-full.csv` file and contains a hard coded override for `.mil` addresses but this code should be updated to pull in a second resource file with CG controlled overrides as a secure resource as to not have to make code changes for overrides in the future.

**Comment by bengerman13** [comment]
The first step here is to determine criteria for groups to allow self-registration and sandboxes for. We should consult the SSP to see if it's spelled out there.

**Comment by bengerman13** [comment]
@LindsayYoung are we ok to add si.edu, based on our conversations in slack and over at cisagov/dotgov-data#54 ?

**Comment by LindsayYoung** [comment]
Yes, after consultation with CISA, [si.edu](http://si.edu/) is a federal domain for our purposes.

Approved
